/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var jis = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,15],$V1=[1,20],$V2=[14,16],$V3=[32,36],$V4=[1,40],$V5=[2,10],$V6=[1,38],$V7=[1,39],$V8=[1,44],$V9=[30,33],$Va=[1,50],$Vb=[1,51],$Vc=[20,40],$Vd=[17,20,33,40];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"expressions":3,"bloque_analizar":4,"EOF":5,"WISON":6,"INTERROGACIONA":7,"bloque_lexico":8,"bloque_sintactico":9,"INTERROGACIONC":10,"LEXP":11,"INICIOLEX":12,"bloque_terminales":13,"FINLEX":14,"terminal1":15,"TERMINAL":16,"IDTERMINAL":17,"ASIGNAR":18,"asignacion_terminal":19,"PUNTOC":20,"CARACTER":21,"TODAS":22,"numerando":23,"NUMEROS":24,"ESTRELLA":25,"CERRADURA":26,"SYNTAXP":27,"INICIOSYN":28,"bloque_no_terminales":29,"FINSYN":30,"bloque_asignacion_no":31,"SIMBOLOINICIAL":32,"IDNOTERMINAL":33,"bloque_producciones":34,"asignacion_no_terminal":35,"NOTERMINAL":36,"produccion":37,"ASIGNARNOTERMINAL":38,"bloque_cadena":39,"OR":40,"cadena":41,"parte_produccion":42,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",6:"WISON",7:"INTERROGACIONA",10:"INTERROGACIONC",11:"LEXP",12:"INICIOLEX",14:"FINLEX",16:"TERMINAL",17:"IDTERMINAL",18:"ASIGNAR",20:"PUNTOC",21:"CARACTER",22:"TODAS",24:"NUMEROS",25:"ESTRELLA",26:"CERRADURA",27:"SYNTAXP",28:"INICIOSYN",30:"FINSYN",32:"SIMBOLOINICIAL",33:"IDNOTERMINAL",36:"NOTERMINAL",38:"ASIGNARNOTERMINAL",40:"OR"},
productions_: [0,[3,2],[4,6],[8,4],[13,2],[13,1],[15,5],[19,1],[19,2],[19,2],[23,0],[23,1],[23,1],[23,1],[9,4],[29,5],[31,2],[31,1],[35,3],[34,2],[34,1],[37,4],[39,3],[39,1],[41,2],[41,1],[42,1],[42,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 return $$[$0-1];
break;
case 2:
 this.$ = instruccionesAPI.nuevaListaTerms($$[$0-3],$$[$0-2]); 
break;
case 3: case 14:
 this.$ = $$[$0-1]; 
break;
case 4:
 $$[$0-1].push($$[$0]); this.$ = $$[$0-1]; 
break;
case 5:
 this.$ = instruccionesAPI.nuevoListaTerminales($$[$0]);
break;
case 6:
this.$ = instruccionesAPI.nuevoTerminalAgregar($$[$0-3],$$[$0-1]);
break;
case 7: case 11: case 12: case 13:
 this.$ = $$[$0];
break;
case 8: case 9:
 this.$ = $$[$0-1]+$$[$0];
break;
case 10:
 this.$ = "";
break;
case 15:
this.$ = instruccionesAPI.nuevaSintactico($$[$0-4],$$[$0-2],$$[$0]);
break;
case 16: case 24:
$$[$0-1].push($$[$0]); this.$ = $$[$0-1]
break;
case 17:
 this.$ = instruccionesAPI.nuevoListaNoTerminales($$[$0]);
break;
case 18:
this.$ = instruccionesAPI.nuevoNoTerminalAgregar($$[$0-1]);
break;
case 19:
$$[$0-1].push($$[$0]); this.$ = $$[$0-1];
break;
case 20:
 this.$ = instruccionesAPI.nuevaListaProduccion2($$[$0]);
break;
case 21:
 this.$ = instruccionesAPI.nuevaProduccion($$[$0-3],this._$.first_line,this._$.first_column,temp); temp=[];
break;
case 22: case 23:
 temp.push(instruccionesAPI.nuevaCadena($$[$0]));
break;
case 25:
 this.$ = instruccionesAPI.nuevaListaProduccion($$[$0]);
break;
case 26: case 27:
 this.$ = instruccionesAPI.nuevoParte($$[$0],this._$.first_line,this._$.first_column);
break;
}
},
table: [{3:1,4:2,6:[1,3]},{1:[3]},{5:[1,4]},{7:[1,5]},{1:[2,1]},{8:6,11:[1,7]},{9:8,27:[1,9]},{12:[1,10]},{10:[1,11]},{28:[1,12]},{13:13,15:14,16:$V0},{6:[1,16]},{29:17,31:18,35:19,36:$V1},{14:[1,21],15:22,16:$V0},o($V2,[2,5]),{17:[1,23]},{5:[2,2]},{30:[1,24]},{32:[1,25],35:26,36:$V1},o($V3,[2,17]),{33:[1,27]},{27:[2,3]},o($V2,[2,4]),{18:[1,28]},{10:[2,14]},{33:[1,29]},o($V3,[2,16]),{20:[1,30]},{19:31,21:[1,32],22:[1,33],24:[1,34]},{20:[1,35]},o($V3,[2,18]),{20:[1,36]},{20:[2,7]},{10:$V4,20:$V5,23:37,25:$V6,26:$V7},{10:$V4,20:$V5,23:41,25:$V6,26:$V7},{33:$V8,34:42,37:43},o($V2,[2,6]),{20:[2,8]},{20:[2,11]},{20:[2,12]},{20:[2,13]},{20:[2,9]},{30:[2,15],33:$V8,37:45},o($V9,[2,20]),{38:[1,46]},o($V9,[2,19]),{17:$Va,33:$Vb,39:47,41:48,42:49},{20:[1,52],40:[1,53]},o($Vc,[2,23],{42:54,17:$Va,33:$Vb}),o($Vd,[2,25]),o($Vd,[2,26]),o($Vd,[2,27]),o($V9,[2,21]),{17:$Va,33:$Vb,41:55,42:49},o($Vd,[2,24]),o($Vc,[2,22],{42:54,17:$Va,33:$Vb})],
defaultActions: {4:[2,1],16:[2,2],21:[2,3],24:[2,14],32:[2,7],37:[2,8],38:[2,11],39:[2,12],40:[2,13],41:[2,9]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

	const instruccionesAPI	= require('./instrucciones').instruccionesAPI;
	var temp = []; 
	var conteo = 0;
	var doble = [];
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 6
break;
case 1:return 7
break;
case 2:return 11
break;
case 3:return 12
break;
case 4:return 16
break;
case 5:return 36
break;
case 6:return 27
break;
case 7:return 32
break;
case 8:return 28
break;
case 9:return 18
break;
case 10:return 38
break;
case 11:return 20
break;
case 12:return 40
break;
case 13:return 17
break;
case 14:return 33
break;
case 15:this.begin("string");
break;
case 16:return "CARACTER";
break;
case 17:this.popState();
break;
case 18:return 22
break;
case 19:return 24
break;
case 20:return 26
break;
case 21:return 10
break;
case 22:return 30
break;
case 23:return 25
break;
case 24:return 14
break;
case 25:return 'NUMBER'
break;
case 26:return 'LETRAS'
break;
case 27:this.begin("coment");
break;
case 28:/*return "COMENTARIO";*/
break;
case 29:this.popState();
break;
case 30:this.begin("coment2");
break;
case 31:/*return "COMENTARIO";*/
break;
case 32:this.popState();
break;
case 33:/*solo ignora*/
break;
case 34:return 5
break;
case 35:return 'INVALID'
break;
}
},
rules: [/^(?:([wW][iI][sS][oO][nN]))/,/^(?:¿)/,/^(?:([lL][eE][xX]))/,/^(?:\{:)/,/^(?:([tT][eE][rR][mM][iI][nN][aA][lL]))/,/^(?:([nN][oO]_[tT][eE][rR][mM][iI][nN][aA][lL]))/,/^(?:([sS][yY][nN][tT][aA][xX]))/,/^(?:([iI][nN][iI][tT][iI][aA][lL]_[sS][iI][mM]))/,/^(?:\{\{:)/,/^(?:<-)/,/^(?:<=)/,/^(?:;)/,/^(?:(\||OR))/,/^(?:\$_(([a-zA-Z]+([a-zA-Z]|[0-9]+)*)|_)+)/,/^(?:%_(([a-zA-Z]+([a-zA-Z]|[0-9]+)*)|_)+)/,/^(?:('|‘))/,/^(?:[^'’]+)/,/^(?:('|’))/,/^(?:\[aA-zZ\])/,/^(?:\[0-9\])/,/^(?:\+)/,/^(?:\?)/,/^(?::\}\})/,/^(?:\*)/,/^(?::\})/,/^(?:(-?([0-9]|[1-9][0-9]+))(\.[0-9]+)?\b)/,/^(?:([a-zA-Z]+))/,/^(?:(#))/,/^(?:[^\n]+)/,/^(?:[\n])/,/^(?:[/**])/,/^(?:[^*/]+)/,/^(?:[*/])/,/^(?:([\s|\n|\t|\r]+))/,/^(?:$)/,/^(?:.)/],
conditions: {"coment2":{"rules":[31,32],"inclusive":false},"coment":{"rules":[28,29],"inclusive":false},"string":{"rules":[16,17],"inclusive":false},"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,18,19,20,21,22,23,24,25,26,27,30,33,34,35],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = jis;
exports.Parser = jis.Parser;
exports.parse = function () { return jis.parse.apply(jis, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}